### ISSUE TITLE
Some warnings reported by Maven 3.9.2

### ISSUE THREAD

**Issue by cowtowncoder** [jjohannes/gradle-module-metadata-maven-plugin#14]
Looks like Maven is starting to report warning about various plug-ins, and there are couple for 0.4.0 version of this plugin.
With VERBOSE settings (`./mvnw clean package -Dmaven.plugin.validation=DEFAULT`) I see this:

```
[WARNING]  * de.jjohannes:gradle-module-metadata-maven-plugin:0.4.0
[WARNING]   Declared at location(s):
[WARNING]    * com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.16.0-SNAPSHOT (pom.xml) @ line 185
[WARNING]   Used in module(s):
[WARNING]    * com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.16.0-SNAPSHOT (pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-core:3.6.0, org.apache.maven:maven-plugin-api:3.6.0, org.apache.maven:maven-model-builder:3.6.0, org.apache.maven:maven-model:3.6.0, org.apache.maven:maven-builder-support:3.6.0, org.apache.maven:maven-settings:3.6.0, org.apache.maven:maven-resolver-provider:3.6.0, org.apache.maven:maven-settings-builder:3.6.0, org.apache.maven:maven-repository-metadata:3.6.0, org.apache.maven:maven-artifact:3.6.0]
```

it sounds like scope declarations and hopefully is easy to resolve.

**Comment by jjohannes** [comment]
Thanks for reporting. I'll get this fixed.

**Comment by jjohannes** [comment]
I am puzzled by this, as the scopes are declared as expected. E.g.: https://github.com/jjohannes/gradle-module-metadata-maven-plugin/blob/main/pom.xml#L55

They are also shown correctly in the published `pom` (https://mvnrepository.com/artifact/de.jjohannes/gradle-module-metadata-maven-plugin/0.4.0).

**Comment by cowtowncoder** [comment]
Could be something wrong with Maven 3.9.2 release; apparently 3.9.3 is to fix some issues and should be out soon.

So perhaps it could be false alarm?

**Comment by cowtowncoder** [comment]
I suspect Maven 3.9.2 was the culprit here; have not seen further issues on my side either.
