### ISSUE TITLE
Is this published anywhere?

### ISSUE THREAD

**Issue by mwisnicki** [jjohannes/gradle-module-metadata-maven-plugin#8]

**Comment by jjohannes** [comment]
Yes this Maven plugin is [published on Maven Central](https://mvnrepository.com/artifact/de.jjohannes/gradle-module-metadata-maven-plugin).

You can apply it in your Maven build as described in the [README](https://github.com/jjohannes/gradle-module-metadata-maven-plugin/blob/master/README.MD#using-the-plugin).
